### ISSUE TITLE
No such file or directory: 'data/moves/moves_2005.txt'

### ISSUE THREAD

**Issue by Kidrauhl70** [msaebi1993/Species-Flow-Networks#1]
Hi, 
I was trying to run `00_sort_clean_moves.ipynb` and a error occured `No such file or directory: 'data/moves/moves_2005.txt'`. And then I checked the data folder, there did not exist the moves folder or something similar.
I really can't find the corresponding file in the data folder. Could you please upload the files or tell me where to find it? 
Thanks!

**Comment by msaebi1993** [comment]
Hi,

Thanks for reaching out. Unfortunately, I can't provide that data since
it's the property of Lloyd's . The data was purchased for a research study
and can't be made available publicly.

Best,
Mandana

**Comment by Kidrauhl70** [comment]
Thanks for your time.  :)
